# audio.rpy

define audio.BGM_SPRING = "bgm_spring_morning.ogg"
define audio.BGM_NOISY = "bgm_noisy_hallway.ogg"
define audio.BGM_LAZY = "bgm_lazy_afternoon.ogg"
define audio.BGM_HARIN = "bgm_theme_harin.ogg"
define audio.BGM_YUNA = "bgm_theme_yuna.ogg"
define audio.BGM_SEOLA = "bgm_theme_seola.ogg"
define audio.BGM_GAEUN = "bgm_theme_gaeun.ogg"
define audio.BGM_GLITCH = "bgm_glitch_smile.ogg"
define audio.BGM_ANXIETY = "bgm_creeping_anxiety.ogg"
define audio.BGM_DISTANCE = "bgm_uncomfortable_distance.ogg"
define audio.BGM_TRAUMA_H = "bgm_trauma_harin.ogg"
define audio.BGM_TRAUMA_Y = "bgm_trauma_yuna.ogg"
define audio.BGM_TRAUMA_S = "bgm_trauma_seola.ogg"
define audio.BGM_TRAUMA_G = "bgm_trauma_gaeun.ogg"
define audio.BGM_FLASHBACK = "bgm_seojin_flashback.ogg"
define audio.BGM_CHOICE = "bgm_night_of_choice.ogg"
define audio.BGM_STANDBY = "bgm_stand_by_you.ogg"
define audio.BGM_END_FADEOUT = "bgm_end_fadeout.ogg"
define audio.BGM_END_RUIN = "bgm_end_ruin.ogg"
define audio.BGM_END_TRUE = "bgm_end_true.ogg"

define audio.SE_BELL = "se_bell.ogg"
define audio.SE_DOOR = "se_door.ogg"
define audio.SE_FOOTSTEP = "se_footstep.ogg"
define audio.SE_PHONE = "se_phone_buzz.ogg"
define audio.SE_CAMERA = "se_camera.ogg"
define audio.SE_WIND = "se_wind.ogg"
define audio.SE_PEN = "se_pen_click.ogg"
define audio.SE_CANDY = "se_candy_wrapper.ogg"
define audio.SE_PAGE = "se_page_turn.ogg"
define audio.SE_COUGH = "se_cough.ogg"
define audio.SE_HEARTBEAT = "se_heartbeat.ogg"
define audio.SE_GLASS = "se_glass_crack.ogg"
define audio.SE_SLAP = "se_slap.ogg"
define audio.SE_SCRATCH = "se_scratch.ogg"
define audio.SE_VOMIT = "se_vomit.ogg"
